### ISSUE TITLE
Question: Immutable transformations?

### ISSUE THREAD

**Issue by rstacruz** [syntax-tree/unist-util-visit#12]
Is it possible to modify nodes in an immutable way? eg,

```js
// Redact all text nodes
node = visit(node, (child) => {
  if (child.type === 'text') {
    return { ...child, value: '[redacted]' }
  }
})
```

**Comment by rstacruz** [comment]
looks like [unist-util-map](https://yarnpkg.com/en/package/unist-util-map) is what i'm looking for :)

**Comment by wooorm** [comment]
Yup, that works! In most cases, I’d suggest treating the tree as a state, and suggest mutating it, but when needed, you could also clone the tree and mutate that?

**Comment by giuseppeg** [comment]
@wooorm would you still suggest to mutate the tree two years later?

**Comment by wooorm** [comment]
Yes, I do.
Plugins are always the slowest in the unified process.
Copying a syntax-tree for 1mb of say markdown is a gigantically slow operation.
Mutating a couple of things is faster.

**Comment by giuseppeg** [comment]
Sweet! I know that this is really subjective and depends on my needs but do you have any favorite traversal library? I see that there are many out there. Thank you :)

**Comment by wooorm** [comment]
`unist-util-visit` is almost always good enough, and `unist-util-visit-parents` (used in the former) if you need to access all parents
