### ISSUE TITLE
Special character parsing

### ISSUE THREAD

**Issue by iamskok** [syntax-tree/unist-util-visit#14]
Hey, @wooorm 👋 

I'm working on Gatsby plugin for extending code block functionality and it's using the below syntax:

``````
```js:title=index.js&copy=true
console.log('Some code goes here...')
```
``````

The problem I'm facing is that `&copy` gets encoded to `©`. Is there any way to avoid it?

**Comment by ChristianMurphy** [comment]
Hey @iamskok! :wave: 
This question is related to Remark/Mdast parsing, the best place to ask it would be https://spectrum.chat/unified/remark.
It's not something that can be fixed/added to `unist-util-visit`.

**Comment by iamskok** [comment]
@ChristianMurphy Thank you!
