### ISSUE TITLE
typings: add typescript typings

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/unist-util-visit#15]
### Subject of the feature

Add Typescript typings for `unist-util-visit`

### Problem

projects have to `// @ts-ignore` or manually add typings

### Expected behaviour

Typings should be provided

### Notes

This plugin is one of the more common utils used in transforms, the typings here can help inform a decision on https://github.com/unifiedjs/unified/issues/65

This may be able to leverage https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/unist-util-is/index.d.ts

**Comment by ChristianMurphy** [comment]
Ideally when a function is passed as a `test`, it should be able to define a type predicate, and verify that the type passed to the visitor matches
https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates

**Comment by ChristianMurphy** [comment]
Also ideally if a string is passed for a `test`, TypeScript should verify that the string value matches the `type` of the node.
For example

```ts
interface HeadingNode extends ParentNode {
  type: 'heading'
  depth: number
}

// valid
unistUntiVisit(tree, 'heading', (node: HeadingNode) => {...})

// not valid
unistUntiVisit(tree, 'not-a-heading', (node: HeadingNode) => {...})
```

**Comment by wooorm** [comment]
How would type work with the different syntax es, and with custom nodes?

**Comment by ChristianMurphy** [comment]
My goal is to keep it generic.
The only requirement that I am aware of is that what gets passed as `tree` and what gets passed as `node`, must extend unist `Node`. In that they must have a `type`attribute.
Everything else should be flexible enough to support `unist`, `mdast`, `mdxast`, `hast` and `redot`.

**Comment by wooorm** [comment]
Perfect!

**Comment by ChristianMurphy** [comment]
https://github.com/syntax-tree/unist-util-visit/pull/16/files#diff-fbc098e48a28691a544d0b13581a96af should give a better picture of how this can work cross-project.
There are tests for a remark `heading` node and a rehype `element` node.

**Comment by wooorm** [comment]
Released as well!
