### ISSUE TITLE
[Types]: type of parent should be Parent

### ISSUE THREAD

**Issue by christianvoigt** [syntax-tree/unist-util-visit#17]
Hi, currently the type for Visitor is 

```
  type Visitor<V extends Node> = (
    node: V,
    index: number,
    parent: Node
  ) => void | Action | Index | ActionTuple
```

I think the parent parameter should be of type `Parent`, as the type `Node` does not have a children property.

**Comment by ChristianMurphy** [comment]
Thanks @christianvoigt ,
`parent` parameter can be `Parent` or `undefined` a PR updating the typings would be welcome!

**Comment by wooorm** [comment]
@christianvoigt Are you interested and able to work on a PR fixing this?

**Comment by wooorm** [comment]
@christianvoigt Ping! 🙂
