### ISSUE TITLE
Standalone documentation

### ISSUE THREAD

**Issue by benatkin** [syntax-tree/unist-util-visit#20]
### Subject of the feature

I think it would be easier to get started with this if the README contained the docs about common things like returning an action instead of referring to unist-util-visit-parents.

### Problem

It took me a little while to figure out that, like unist-util-visit-parents, this accepts returning an action (such as `visit.SKIP`).

### Alternatives

Removing the details of how to call the function and just linking to unist-util-visit-parents might work.

**Comment by wooorm** [comment]
Hmm. The alternative isn’t great, because there are differences. And I don’t think copy/pasting most of the docs will help either, because then you’re also lost comparing the two.

There’s a link to `visit-parents` in every paragraph in the API section already, I’d say that’s enough?

**Comment by benatkin** [comment]
It doesn't say to follow the link for more documentation, so I didn't that it contains more help for this package at first.

**Comment by ChristianMurphy** [comment]
> It doesn't say to follow the link for more documentation, so I didn't that it contains more help for this package at first.

I read the line:

> Otherwise the same as [unist-util-visit-parents](https://github.com/syntax-tree/unist-util-visit-parents).

in the readme as saying that already.
Though I'm open to another concise alternative.
