### ISSUE TITLE
NPM readme example still uses require()

### ISSUE THREAD

**Issue by justinfagnani** [syntax-tree/unist-util-visit#24]
### Initial checklist

*   [ ] I read the support docs 
*   [ ] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

The example in the readme on main uses `import`, so it seems like just a new publish is needed.

**Comment by wooorm** [comment]
Fixed!
