### ISSUE TITLE
Types not regonized on nodes

### ISSUE THREAD

**Issue by kam-st** [syntax-tree/unist-util-visit#37]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unist-util-visit

### Steps to reproduce

In following code cannot find types for tagName, properties and children.

```
const result = await unified()
    .use(remarkParse, { fragment: true })
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(() => {
      return (tree) => {
        console.log(tree);
        visit(tree, 'element', (node) => {
          // @ts-ignore
          if (node.tagName == 'h2') {
            // console.log(node);
            // @ts-ignore
            const id = node.properties.id;
            // @ts-ignore
            const heading = node.children[0].value;
            toc.push({ id, title: heading });
          }
        });
      };
    })
    .use(rehypeStringify)
    .process(fileContent);

  return toc;
}
```

### Expected behavior

Types should be recognized. 

### Actual behavior

node is of type 'never'

### Affected runtime and version

node@20 lts

**Comment by wooorm** [comment]
Type your plugin. See all plugins for how to do it.

**Comment by ChristianMurphy** [comment]
Adding on, there is a guide on this very topic you can reference @kam-st https://unifiedjs.com/learn/recipe/tree-traversal-typescript/

**Comment by omonk** [comment]
I'm doing something along the same lines but the typings aren't working for me when I'm using Root from hast

```
import remarkParse from 'remark-parse';
import remarkRehype from 'remark-rehype';
import { unified } from 'unified';
import { visit } from 'unist-util-visit';
import { is } from 'unist-util-is';
import type { Root  } from 'hast';

unified()
    .use(remarkParse)
    .use(remarkRehype)
    .use(() => (hast: Root) => {
      visit(hast, 'element', (node) => {
        const isAnchor = is(node, 'anchor');

        if (isAnchor) {
          const href = node.properties.href; 
        }
      });
    })
```

The visitor node type is `Element`, but selecting `node.properties` results in a TS error

```
Property 'properties' does not exist on type 'never'.
  The intersection 'Element & Node & { type: "anchor"; }' was reduced to 'never' because property 'type' has conflicting types in some constituents.
```

The node from remarkRehype will be a Root  `hast` will it not?

**Comment by wooorm** [comment]
The explanation is sometimes the simplest possible explanation: You get a type error because you have a type error.

`'anchor'` is not an existing node type in hast (that is what you check by using `unist-util-is`).
`'anchor'` is also not an element name known to HTML (that is what you would check by using `hast-util-is`).

No clue what you are doing

**Comment by omonk** [comment]
Thank you for such a speedy reply! I was probably just getting a bit confused with all the different types exported. This works without any TS issues now.

```
import { type Root } from 'hast';
import { isElement } from 'hast-util-is-element'; 
import { hasProperty } from 'hast-util-has-property';

// 

.use(() => (hast: Root) => {
  visit(hast, 'element', (node) => {
    const isAnchor = isElement(node, 'a');
    const hasHref = hasProperty(node, 'href');

    if (isAnchor && hasHref) {
      const href = node.properties.href;
      const parsed = path.parse(href as string);

      if (parsed.root === '/') {
        classnames(node, ['js-hook__internal-md-link']);
      }
    }
  });
})```

**Comment by wooorm** [comment]
you might not need those utilities:

```diff
-   const isAnchor = isElement(node, 'a');
-   const hasHref = hasProperty(node, 'href');
-
-   if (isAnchor && hasHref) {
+   if (node.tagName === 'a' && node.properties.href) {
```

**Comment by omonk** [comment]
Maybe not but it makes me look like I know what I'm doing to the rest of my colleagues. 

My pleasure, thank you for all of your work 🙏

**Comment by karlhorky** [comment]
> Type your plugin. See all plugins for how to do it.

What does the plugin typing have to do with it? Shouldn't `visit()` already return a non-`any` / non-`never` type for `node`, given some valid string?

Eg. given the DX of other TypeScript- or JSDoc-supporting libraries, I would expect with a simple call to `visit()`, `node` would already be typed:

```ts
import {Node} from 'unist';
import { visit } from 'unist-util-visit';
import '@types/unist';

visit({} as Node, 'element', (node) => {
                           // ^? never
});
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwHIQCYFMC+cBmUIhwDkArgHbADOMRA3AFCiSyJwBuVw82eBx5VGAFoSMYABshHSlzqNw0eEQACMAJ5h0lAPQDqc+tK4AKBNgCGlOCgwAaYunHoQ6MjXvGyadAEo4AXgA+RHo4MPCIyKio7W04AD0AfnpMHwYgA)

Also, it would be awesome for type discoverability if the `check` supported IntelliSense suggestions:

![Screenshot 2024-07-21 at 18 15 09](https://github.com/user-attachments/assets/59469222-5ddf-40d3-a754-18eb1e36157b)

Happy to open new separate issues for either of these, if they are accepted.

**Comment by karlhorky** [comment]
> Type your plugin. See all plugins for how to do it.

Also, separately, related to plugin typing:

Is there an easy-to-find example of how to get proper types without `any` or `never` in some remark plugin?

Looking through [the List of Plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins), I found many which do not show typing related to the `node` in the original example:

- [`remark-img-links`](https://github.com/pondorasti/remark-img-links/blob/main/index.js) (no types)
- [`remark-images`](https://github.com/remarkjs/remark-images/blob/main/lib/index.js) (no types for `node` in `visitParents()` callback)
- more...

**Comment by karlhorky** [comment]
Hmm... after digging for a while, it seems like [`remark-code-title`](https://github.com/kevinzunigacuellar/remark-code-title/blob/main/packages/remark-code-title/src/remarkPlugin.ts) may have working types for this:

```ts
import { visit } from "unist-util-visit";
import type * as mdast from "mdast";
import type * as unified from "unified";

export const remarkCodeTitle: unified.Plugin<[], mdast.Root> = () => {
  return (tree, file) => {
    visit(tree, "code", (node, index, parent) => {
                       // ^? mdast.Code
    })
  }
}
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgN2AZ2PAvnAZlCEOAIgFcA7dGAWlJmABtrUMZiBuAKFEljhgCeYAKZwAVHACGaOCAAm0+PkIl5ijt3DR4gkeKkyKwXMGFy8BImUomzGzsIAeveAGMI5NPCjCQkqADWAMIQcsIAKpgMwgBccEa2cgB0AAoMpADmwOQAPADaALoANLIKXkkAShAQMAB8cAC8cAAUAJSN9QiccHA+MKRQ5C0wPsIlJtHtDZ3dPSjomM0jwmMk7mHEJc3koavZYY4lYP7C5DBTM3NX1zdXAPR3cAB6APyzPVits1icP0A)

Not sure if this is the right thing to do, but this looks like the closest so far... 🤔

**Comment by karlhorky** [comment]
For anyone else coming here while trying to build a remark plugin:

Seems that the key for a remark plugin is this `mdast.Root` type, which needs to be manually set.

And then an element type that would work here would be eg. `'image'`, which will return the `mdast.Image` type:

```ts
import {Root} from 'mdast';
import { visit } from 'unist-util-visit';

visit({} as Root, 'image', (node) => {
                         // ^? mdast.Image
});
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwEoQjAvnAZlCI4DkIAJgIYDOMBA3AFCiSyJwBuw5w8mOehArgDt2MALR8YwADYi2HKnVqzOACgSYKcFGgA0hUKQDmAUwK7lAiMSMBKOAF4AfIlpxXb9x8-uA9N7gA9AH5adGs6IA)

To follow the recommendation to type the plugin, then it would look like [the `remark-code-title` example](https://github.com/syntax-tree/unist-util-visit/issues/37#issuecomment-2241704386):

```ts
import { visit } from "unist-util-visit";
import type { Root } from "mdast";
import type { Plugin } from "unified";

export const remarkCodeTitle: Plugin<[], Root> = () => {
  return (tree, file) => {
    visit(tree, "image", (node, index, parent) => {
                       // ^? mdast.Image
    })
  }
}
```

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgN2AZ2PAvnAZlCEOAIgFcA7dGAWlJmABtrUMZiBuAKFEljhgCeYAKaI4AJQgRseAkWIgAJgEM0bLj2jxBIsQAUGpAObBycHPkIkKwXMGGKOnTsIAeveAGMI5NXCjCIMpQANYAwhCKwgAqmAzCAFxwBsamADwA2gC6ADQSUjAAfHAAvHAAFACUpcUInHD+wjCkUGblMAHCeXbx1SW19Q0o6JjtnXnEoMpGwsR55eSRXXCmUa55YMHC5DB9A0MHh0eHAPQncAB6APyDDViVg1icWEA)

With JSDoc, it doesn't appear to be easy to get a typed `node` out without multiple manual annotations 🤔 :

```js
import { visit } from "unist-util-visit";

// Only for TS Playground demo to download modules
import 'unified';
import 'mdast';

/** @type {import('unified').Plugin<[], import('mdast').Root>} */
export const remarkCodeTitle = () => {
  /**
   * @param {import('mdast').Root} tree
   */
  return (tree, file) => {
    visit(tree, "image",
      /**
       * @param {import('mdast').Image} node
       */
      (node, index, parent) => {
      // ^? mdast.Image
      }
    )
  }
}
```

[Playground](https://www.typescriptlang.org/play/?filetype=js#code/JYWwDg9gTgLgBAbzgN2AZ2PAvnAZlCEOAIgFcA7dGAWlJmABtrUMZiBuAKE4Hoe4A8uQYBPPNDgATAKYgInUJFhwA5BWC5g0ySq6Lo8FSEkBDNDF3ceAKmtwAAjBFhpifbAAUaypu0qAlAB0AAoMpADmwOQAPADaALoANHDuMF7GZhZBAEoQEDAAfDjWPJzSAB5K8ADGEOTmcFCyJlAA1gDCEDIAKpgMrgC8cB7+cAMFiJxwcDbWU9N29mAtJkQIqemm5gGBufk4ME3S83Al800wpFDkw4fS0sma-aPjk9PTLJgedw8koCbhaTERInd6zUHvRbLKCrNzgAybTI7ACSIAB0hw5C6x3euLOuOmHixMmSURk5WS0Ok5BgLwmCAhM34AD0APyMrCg-zzTmcoA)

**Comment by wooorm** [comment]
Type the input. This issue is posted at a utility. So how to type things depends. If you are making plugins as you are doing here, then it means typing the plugins. You do not need `Plugin`. Adding types to things, in this case parameters, is fine:

```js
/**
 * @import {Root} from 'mdast'
 */

import {visit} from 'unist-util-visit'

export function myPlugin() {
  /**
   * @param {Root} tree
   * @returns {undefined}
   */
  return function (tree) {
    visit(tree, 'image', function (node) {
      // `node` is typed.
    })
  }
}
```

**Comment by wooorm** [comment]
I would not recommend looking at one particular userland example and base all your thinking on it. Instead, look at several examples, particularly the ones maintained by us. For remark, look in the remark organization: https://github.com/orgs/remarkjs/repositories?type=source.

**Comment by karlhorky** [comment]
> Type the input. This issue is posted at a utility. So how to type things depends. If you are making plugins as you are doing here, then it means typing the plugins. You do not need `Plugin`. Adding types to things, in this case parameters, is fine:

That would be a bit better, but it doesn't seem to yield a non-`any` type with JSDoc:

```js
/**
 * @import {Root} from 'mdast'
 */

import { visit } from "unist-util-visit";

// Only for demo
import 'unified';
import 'mdast';

export function myPlugin() {
  /**
   * @param {Root} tree
   * @returns {undefined}
   */
  return function (tree) {
    visit(tree, 'image', function (node) {
                                // ^? any
    })
  }
}
```

[Playground](https://www.typescriptlang.org/play/?filetype=js#code/PQKhCgAIUgBBLAtgBwPYCcAukDeAlVVTAX0gDN1VFIByRAEwEMBnTGqEYccJNLXSADd4zeNlIUqkAEQBXAHYjMAWlmZ4AG2XDRmaQG5uwYJADy8jQE9yGSPQCmiVDxQZsNBfDLx79God43WgYWNkNwewAPPmwyBQBjdVR5SERLAAUNWQBzeHkACgBKXChIUAhISphYZEZ0Rmp8QhJITHR7e1LoOHbMWXR5ZlwFB295X2IuzlLe-pS4+UT4ZMh8to7inC6hETE19vsAGlokRmz7GmOFpZX8+VQHTe3Kl9e394+ykwA9AH5t4iFUqTSZAA)

**Comment by wooorm** [comment]
I do not know why your playground doesn’t work. It works locally, and that is how I have typed 100s of projects

**Comment by remcohaszing** [comment]
For some reason the playground is unable to load the unist types. As a result, the type of `node` is not `any`. It is unresolved `any` (see https://github.com/microsoft/TypeScript/issues/58960). This is why `node` is not properly resolved on the playground. The `unist-util-visit` types are working correctly. Please report an issue with the TypeScript playground.

**Comment by karlhorky** [comment]
Not sure that's related - I think the `import 'mdast';` line is working to load `@types/mdast`, hovering over `Root` in [the playground](https://github.com/syntax-tree/unist-util-visit/issues/37#:~:text=)%0A%20%20%7D%0A%7D-,Playground,-I%20can%20open) shows the type information:

![Screenshot 2024-07-22 at 12 09 12](https://github.com/user-attachments/assets/03d3e468-947b-4ee6-9eb0-bf3b89c37d1f)

![Screenshot 2024-07-22 at 12 11 40](https://github.com/user-attachments/assets/ce9f5a84-81ea-4c10-8cfe-46a8bb0b5126)

Maybe [Remco's comment](https://github.com/syntax-tree/unist-util-visit/issues/37#issuecomment-2242414550) indicates an unresolved `any` somewhere...? I can't observe this anywhere in local IDE environment though.

**Comment by remcohaszing** [comment]
`@types/mdast` is resolved fine in the playground, `@types/unist` is not. Hence there’t an unresolved `any` in the playground, but not locally. This can be observed in the network requests made as well. This issue is not related to our types.

:point_down: 

> Please report an issue with the TypeScript playground.

**Comment by karlhorky** [comment]
Reported a TypeScript Playground issue:

- https://github.com/microsoft/TypeScript-Website/issues/3187
